exclude_dirs:
  - vendor
  - node_modules
  - .git
  - dist
  - build

max_file_size_bytes: 1048576

enable_entropy: false
entropy_threshold: 4.7
min_entropy_len: 24

# optional: skip known safe tokens/patterns
# allowlist_regex: "^TEST_TOKEN_"
allowlist_regex: ""
